### ISSUE TITLE
How are the shard IDs assigned to each client? 

### ISSUE THREAD

**Issue by MacDue** [Auttaja-OpenSource/Marver#2]
I've had a look through the code & think it could be helpful for my bot. 

I can see where you pass the total number of shards to the container but not the shard ID.
Do you use the stateful set ordinal for this? (if so how do you access it).

**Comment by IAmJSD** [comment]
Hi MacDue,

To get the shard ID you can use the following YAML:
```yaml
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```
And then split the pod name by `-`, pop and parse to an int to get the share ID.

Going to close now since I think this explains what you want to know. Feel free to reply if you have further issues.
